language: java
jdk: oraclejdk8
sudo: false
install: true

addons:
  apt:
    packages:
      - oracle-java8-installer
  sonarcloud:
    organization: "netopyr-github"
script:
  -
  - if [ "TRAVIS_PULL_REQUEST" == false ]; then
      mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent verify sonar:sonar
    else
      mvn clean verify
    fi
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
