language: java
jdk: oraclejdk8
sudo: false
install: true

addons:
  apt:
    packages:
      - oracle-java8-installer
  sonarcloud:
    organization: "netopyr-github"
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent verify sonar:sonar versioneye:update
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
